language: python
services:
  - redis-server
matrix:
  include:
  - python: "2.7"
    env: DJANGO_VERSION=1.11.23
  - python: "3.7"
    env: DJANGO_VERSION=2.0
  - python: "3.7"
    env: DJANGO_VERSION=2.1
  - python: "3.7"
    env: DJANGO_VERSION=2.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-redis-cache
script: python runtests.py
