language: python
services:
  - redis-server
python:
  - '2.6'
  - '2.7'
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-redis-cache
script: python runtests.py
